import { Map } from "../types/types";
import {
  UNSET_CELL as U,
  START_CELL as S,
  END_CELL as E,
} from "../constants/mapMatrixConstants";

const repeatString = (str: string, times: number): string[] => {
  return new Array(times).fill(str);
};

export const burbenogMap: Map = [
  [
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [{ distance: 0, path: "0" }],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
  ],
  [
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [{ distance: 1, path: "0" }],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
  ],
  [
    "?",
    "?",
    [
      { distance: 20, path: "0" },
      { distance: 131, path: "1" },
      { distance: 94, path: "2" },
      { distance: 57, path: "3" },
    ],
    [
      { distance: 21, path: "0" },
      { distance: 132, path: "1" },
      { distance: 95, path: "2" },
      { distance: 58, path: "3" },
    ],
    [
      { distance: 22, path: "0" },
      { distance: 133, path: "1" },
      { distance: 96, path: "2" },
      { distance: 59, path: "3" },
    ],
    [
      { distance: 23, path: "0" },
      { distance: 134, path: "1" },
      { distance: 97, path: "2" },
      { distance: 60, path: "3" },
    ],
    [
      { distance: 24, path: "0" },
      { distance: 135, path: "1" },
      { distance: 98, path: "2" },
      { distance: 61, path: "3" },
    ],
    [
      { distance: 25, path: "0" },
      { distance: 136, path: "1" },
      { distance: 99, path: "2" },
      { distance: 62, path: "3" },
    ],
    [
      { distance: 2, path: "0" },
      { distance: 26, path: "0" },
      { distance: 137, path: "1" },
      { distance: 100, path: "2" },
      { distance: 63, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 125, path: "0" },
      { distance: 88, path: "1" },
      { distance: 51, path: "2" },
      { distance: 14, path: "3" },
    ],
    [
      { distance: 126, path: "0" },
      { distance: 89, path: "1" },
      { distance: 52, path: "2" },
      { distance: 15, path: "3" },
    ],
    [
      { distance: 127, path: "0" },
      { distance: 90, path: "1" },
      { distance: 53, path: "2" },
      { distance: 16, path: "3" },
    ],
    [
      { distance: 128, path: "0" },
      { distance: 91, path: "1" },
      { distance: 54, path: "2" },
      { distance: 17, path: "3" },
    ],
    [
      { distance: 129, path: "0" },
      { distance: 92, path: "1" },
      { distance: 55, path: "2" },
      { distance: 18, path: "3" },
    ],
    [
      { distance: 130, path: "0" },
      { distance: 93, path: "1" },
      { distance: 56, path: "2" },
      { distance: 19, path: "3" },
    ],
    [
      { distance: 131, path: "0" },
      { distance: 94, path: "1" },
      { distance: 57, path: "2" },
      { distance: 20, path: "3" },
    ],
    "?",
    "?",
  ],
  [
    "?",
    "?",
    [
      { distance: 19, path: "0" },
      { distance: 130, path: "1" },
      { distance: 93, path: "2" },
      { distance: 56, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 3, path: "0" },
      { distance: 27, path: "0" },
      { distance: 138, path: "1" },
      { distance: 101, path: "2" },
      { distance: 64, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 124, path: "0" },
      { distance: 87, path: "1" },
      { distance: 50, path: "2" },
      { distance: 13, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 132, path: "0" },
      { distance: 95, path: "1" },
      { distance: 58, path: "2" },
      { distance: 21, path: "3" },
    ],
    "?",
    "?",
  ],
  [
    "?",
    "?",
    [
      { distance: 18, path: "0" },
      { distance: 129, path: "1" },
      { distance: 92, path: "2" },
      { distance: 55, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 4, path: "0" },
      { distance: 28, path: "0" },
      { distance: 139, path: "1" },
      { distance: 102, path: "2" },
      { distance: 65, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 123, path: "0" },
      { distance: 86, path: "1" },
      { distance: 49, path: "2" },
      { distance: 12, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 133, path: "0" },
      { distance: 96, path: "1" },
      { distance: 59, path: "2" },
      { distance: 22, path: "3" },
    ],
    "?",
    "?",
  ],
  [
    "?",
    "?",
    [
      { distance: 17, path: "0" },
      { distance: 128, path: "1" },
      { distance: 91, path: "2" },
      { distance: 54, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 5, path: "0" },
      { distance: 29, path: "0" },
      { distance: 140, path: "1" },
      { distance: 103, path: "2" },
      { distance: 66, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 122, path: "0" },
      { distance: 85, path: "1" },
      { distance: 48, path: "2" },
      { distance: 11, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 134, path: "0" },
      { distance: 97, path: "1" },
      { distance: 60, path: "2" },
      { distance: 23, path: "3" },
    ],
    "?",
    "?",
  ],
  [
    "?",
    "?",
    [
      { distance: 16, path: "0" },
      { distance: 127, path: "1" },
      { distance: 90, path: "2" },
      { distance: 53, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 6, path: "0" },
      { distance: 30, path: "0" },
      { distance: 141, path: "1" },
      { distance: 104, path: "2" },
      { distance: 67, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 121, path: "0" },
      { distance: 84, path: "1" },
      { distance: 47, path: "2" },
      { distance: 10, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 135, path: "0" },
      { distance: 98, path: "1" },
      { distance: 61, path: "2" },
      { distance: 24, path: "3" },
    ],
    "?",
    "?",
  ],
  [
    "?",
    "?",
    [
      { distance: 15, path: "0" },
      { distance: 126, path: "1" },
      { distance: 89, path: "2" },
      { distance: 52, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 7, path: "0" },
      { distance: 31, path: "0" },
      { distance: 142, path: "1" },
      { distance: 105, path: "2" },
      { distance: 68, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 120, path: "0" },
      { distance: 83, path: "1" },
      { distance: 46, path: "2" },
      { distance: 9, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 136, path: "0" },
      { distance: 99, path: "1" },
      { distance: 62, path: "2" },
      { distance: 25, path: "3" },
    ],
    "?",
    "?",
  ],
  [
    "?",
    "?",
    [
      { distance: 14, path: "0" },
      { distance: 125, path: "1" },
      { distance: 88, path: "2" },
      { distance: 51, path: "3" },
    ],
    [
      { distance: 13, path: "0" },
      { distance: 124, path: "1" },
      { distance: 87, path: "2" },
      { distance: 50, path: "3" },
    ],
    [
      { distance: 12, path: "0" },
      { distance: 123, path: "1" },
      { distance: 86, path: "2" },
      { distance: 49, path: "3" },
    ],
    [
      { distance: 11, path: "0" },
      { distance: 122, path: "1" },
      { distance: 85, path: "2" },
      { distance: 48, path: "3" },
    ],
    [
      { distance: 10, path: "0" },
      { distance: 121, path: "1" },
      { distance: 84, path: "2" },
      { distance: 47, path: "3" },
    ],
    [
      { distance: 9, path: "0" },
      { distance: 120, path: "1" },
      { distance: 83, path: "2" },
      { distance: 46, path: "3" },
    ],
    [
      { distance: 8, path: "0" },
      { distance: 32, path: "0" },
      { distance: 119, path: "1" },
      { distance: 143, path: "1" },
      { distance: 82, path: "2" },
      { distance: 106, path: "2" },
      { distance: 45, path: "3" },
      { distance: 69, path: "3" },
    ],
    [
      { distance: 118, path: "1" },
      { distance: 81, path: "2" },
      { distance: 44, path: "3" },
    ],
    [
      { distance: 117, path: "1" },
      { distance: 80, path: "2" },
      { distance: 43, path: "3" },
    ],
    [
      { distance: 116, path: "1" },
      { distance: 79, path: "2" },
      { distance: 42, path: "3" },
    ],
    [
      { distance: 115, path: "1" },
      { distance: 78, path: "2" },
      { distance: 41, path: "3" },
    ],
    [
      { distance: 114, path: "1" },
      { distance: 77, path: "2" },
      { distance: 40, path: "3" },
    ],
    [
      { distance: 113, path: "1" },
      { distance: 76, path: "2" },
      { distance: 39, path: "3" },
    ],
    [
      { distance: 149, path: "0" },
      { distance: 112, path: "1" },
      { distance: 75, path: "2" },
      { distance: 38, path: "3" },
    ],
    [
      { distance: 148, path: "0" },
      { distance: 111, path: "1" },
      { distance: 74, path: "2" },
      { distance: 37, path: "3" },
    ],
    [
      { distance: 147, path: "0" },
      { distance: 110, path: "1" },
      { distance: 73, path: "2" },
      { distance: 36, path: "3" },
    ],
    [
      { distance: 146, path: "0" },
      { distance: 109, path: "1" },
      { distance: 72, path: "2" },
      { distance: 35, path: "3" },
    ],
    [
      { distance: 145, path: "0" },
      { distance: 108, path: "1" },
      { distance: 71, path: "2" },
      { distance: 34, path: "3" },
    ],
    [
      { distance: 144, path: "0" },
      { distance: 107, path: "1" },
      { distance: 70, path: "2" },
      { distance: 33, path: "3" },
    ],
    [
      { distance: 119, path: "0" },
      { distance: 143, path: "0" },
      { distance: 82, path: "1" },
      { distance: 106, path: "1" },
      { distance: 45, path: "2" },
      { distance: 69, path: "2" },
      { distance: 8, path: "3" },
      { distance: 32, path: "3" },
    ],
    [
      { distance: 142, path: "0" },
      { distance: 105, path: "1" },
      { distance: 68, path: "2" },
      { distance: 7, path: "3" },
      { distance: 31, path: "3" },
    ],
    [
      { distance: 141, path: "0" },
      { distance: 104, path: "1" },
      { distance: 67, path: "2" },
      { distance: 6, path: "3" },
      { distance: 30, path: "3" },
    ],
    [
      { distance: 140, path: "0" },
      { distance: 103, path: "1" },
      { distance: 66, path: "2" },
      { distance: 5, path: "3" },
      { distance: 29, path: "3" },
    ],
    [
      { distance: 139, path: "0" },
      { distance: 102, path: "1" },
      { distance: 65, path: "2" },
      { distance: 4, path: "3" },
      { distance: 28, path: "3" },
    ],
    [
      { distance: 138, path: "0" },
      { distance: 101, path: "1" },
      { distance: 64, path: "2" },
      { distance: 3, path: "3" },
      { distance: 27, path: "3" },
    ],
    [
      { distance: 137, path: "0" },
      { distance: 100, path: "1" },
      { distance: 63, path: "2" },
      { distance: 2, path: "3" },
      { distance: 26, path: "3" },
    ],
    [{ distance: 1, path: "3" }],
    [{ distance: 0, path: "3" }],
  ],
  [
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 33, path: "0" },
      { distance: 144, path: "1" },
      { distance: 107, path: "2" },
      { distance: 70, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [{ distance: 150, path: "0" }],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 118, path: "0" },
      { distance: 81, path: "1" },
      { distance: 44, path: "2" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
  ],
  [
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 34, path: "0" },
      { distance: 145, path: "1" },
      { distance: 108, path: "2" },
      { distance: 71, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [{ distance: 151, path: "0" }],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 117, path: "0" },
      { distance: 80, path: "1" },
      { distance: 43, path: "2" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
  ],
  [
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 35, path: "0" },
      { distance: 146, path: "1" },
      { distance: 109, path: "2" },
      { distance: 72, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [{ distance: 152, path: "0" }],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 116, path: "0" },
      { distance: 79, path: "1" },
      { distance: 42, path: "2" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
  ],
  [
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 36, path: "0" },
      { distance: 147, path: "1" },
      { distance: 110, path: "2" },
      { distance: 73, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [{ distance: 153, path: "0" }],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 115, path: "0" },
      { distance: 78, path: "1" },
      { distance: 41, path: "2" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
  ],
  [
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 37, path: "0" },
      { distance: 148, path: "1" },
      { distance: 111, path: "2" },
      { distance: 74, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [{ distance: 154, path: "0" }],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 114, path: "0" },
      { distance: 77, path: "1" },
      { distance: 40, path: "2" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
  ],
  [
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 38, path: "0" },
      { distance: 149, path: "1" },
      { distance: 112, path: "2" },
      { distance: 75, path: "3" },
    ],
    [{ distance: 150, path: "1" }],
    [{ distance: 151, path: "1" }],
    [{ distance: 152, path: "1" }],
    [{ distance: 153, path: "1" }],
    [{ distance: 154, path: "1" }],
    [{ distance: 155, path: "1" }],
    "?",
    [{ distance: 155, path: "3" }],
    [{ distance: 154, path: "3" }],
    [{ distance: 153, path: "3" }],
    [{ distance: 152, path: "3" }],
    [{ distance: 151, path: "3" }],
    [
      { distance: 113, path: "0" },
      { distance: 76, path: "1" },
      { distance: 39, path: "2" },
      { distance: 150, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
  ],
  [
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 39, path: "0" },
      { distance: 113, path: "2" },
      { distance: 76, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [{ distance: 156, path: "2" }],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 112, path: "0" },
      { distance: 75, path: "1" },
      { distance: 38, path: "2" },
      { distance: 149, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
  ],
  [
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 40, path: "0" },
      { distance: 114, path: "2" },
      { distance: 77, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [{ distance: 155, path: "2" }],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 111, path: "0" },
      { distance: 74, path: "1" },
      { distance: 37, path: "2" },
      { distance: 148, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
  ],
  [
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 41, path: "0" },
      { distance: 115, path: "2" },
      { distance: 78, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [{ distance: 154, path: "2" }],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 110, path: "0" },
      { distance: 73, path: "1" },
      { distance: 36, path: "2" },
      { distance: 147, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
  ],
  [
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 42, path: "0" },
      { distance: 116, path: "2" },
      { distance: 79, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [{ distance: 153, path: "2" }],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 109, path: "0" },
      { distance: 72, path: "1" },
      { distance: 35, path: "2" },
      { distance: 146, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
  ],
  [
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 43, path: "0" },
      { distance: 117, path: "2" },
      { distance: 80, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [{ distance: 152, path: "2" }],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 108, path: "0" },
      { distance: 71, path: "1" },
      { distance: 34, path: "2" },
      { distance: 145, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
  ],
  [
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 44, path: "0" },
      { distance: 118, path: "2" },
      { distance: 81, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [{ distance: 151, path: "2" }],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 107, path: "0" },
      { distance: 70, path: "1" },
      { distance: 33, path: "2" },
      { distance: 144, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
  ],
  [
    [{ distance: 0, path: "1" }],
    [{ distance: 1, path: "1" }],
    [
      { distance: 63, path: "0" },
      { distance: 2, path: "1" },
      { distance: 26, path: "1" },
      { distance: 137, path: "2" },
      { distance: 100, path: "3" },
    ],
    [
      { distance: 64, path: "0" },
      { distance: 3, path: "1" },
      { distance: 27, path: "1" },
      { distance: 138, path: "2" },
      { distance: 101, path: "3" },
    ],
    [
      { distance: 65, path: "0" },
      { distance: 4, path: "1" },
      { distance: 28, path: "1" },
      { distance: 139, path: "2" },
      { distance: 102, path: "3" },
    ],
    [
      { distance: 66, path: "0" },
      { distance: 5, path: "1" },
      { distance: 29, path: "1" },
      { distance: 140, path: "2" },
      { distance: 103, path: "3" },
    ],
    [
      { distance: 67, path: "0" },
      { distance: 6, path: "1" },
      { distance: 30, path: "1" },
      { distance: 141, path: "2" },
      { distance: 104, path: "3" },
    ],
    [
      { distance: 68, path: "0" },
      { distance: 7, path: "1" },
      { distance: 31, path: "1" },
      { distance: 142, path: "2" },
      { distance: 105, path: "3" },
    ],
    [
      { distance: 45, path: "0" },
      { distance: 69, path: "0" },
      { distance: 8, path: "1" },
      { distance: 32, path: "1" },
      { distance: 119, path: "2" },
      { distance: 143, path: "2" },
      { distance: 82, path: "3" },
      { distance: 106, path: "3" },
    ],
    [
      { distance: 70, path: "0" },
      { distance: 33, path: "1" },
      { distance: 144, path: "2" },
      { distance: 107, path: "3" },
    ],
    [
      { distance: 71, path: "0" },
      { distance: 34, path: "1" },
      { distance: 145, path: "2" },
      { distance: 108, path: "3" },
    ],
    [
      { distance: 72, path: "0" },
      { distance: 35, path: "1" },
      { distance: 146, path: "2" },
      { distance: 109, path: "3" },
    ],
    [
      { distance: 73, path: "0" },
      { distance: 36, path: "1" },
      { distance: 147, path: "2" },
      { distance: 110, path: "3" },
    ],
    [
      { distance: 74, path: "0" },
      { distance: 37, path: "1" },
      { distance: 148, path: "2" },
      { distance: 111, path: "3" },
    ],
    [
      { distance: 75, path: "0" },
      { distance: 38, path: "1" },
      { distance: 149, path: "2" },
      { distance: 112, path: "3" },
    ],
    [
      { distance: 76, path: "0" },
      { distance: 39, path: "1" },
      { distance: 150, path: "2" },
      { distance: 113, path: "3" },
    ],
    [
      { distance: 77, path: "0" },
      { distance: 40, path: "1" },
      { distance: 114, path: "3" },
    ],
    [
      { distance: 78, path: "0" },
      { distance: 41, path: "1" },
      { distance: 115, path: "3" },
    ],
    [
      { distance: 79, path: "0" },
      { distance: 42, path: "1" },
      { distance: 116, path: "3" },
    ],
    [
      { distance: 80, path: "0" },
      { distance: 43, path: "1" },
      { distance: 117, path: "3" },
    ],
    [
      { distance: 81, path: "0" },
      { distance: 44, path: "1" },
      { distance: 118, path: "3" },
    ],
    [
      { distance: 82, path: "0" },
      { distance: 106, path: "0" },
      { distance: 45, path: "1" },
      { distance: 69, path: "1" },
      { distance: 8, path: "2" },
      { distance: 32, path: "2" },
      { distance: 119, path: "3" },
      { distance: 143, path: "3" },
    ],
    [
      { distance: 83, path: "0" },
      { distance: 46, path: "1" },
      { distance: 9, path: "2" },
      { distance: 120, path: "3" },
    ],
    [
      { distance: 84, path: "0" },
      { distance: 47, path: "1" },
      { distance: 10, path: "2" },
      { distance: 121, path: "3" },
    ],
    [
      { distance: 85, path: "0" },
      { distance: 48, path: "1" },
      { distance: 11, path: "2" },
      { distance: 122, path: "3" },
    ],
    [
      { distance: 86, path: "0" },
      { distance: 49, path: "1" },
      { distance: 12, path: "2" },
      { distance: 123, path: "3" },
    ],
    [
      { distance: 87, path: "0" },
      { distance: 50, path: "1" },
      { distance: 13, path: "2" },
      { distance: 124, path: "3" },
    ],
    [
      { distance: 88, path: "0" },
      { distance: 51, path: "1" },
      { distance: 14, path: "2" },
      { distance: 125, path: "3" },
    ],
    "?",
    "?",
  ],
  [
    "?",
    "?",
    [
      { distance: 62, path: "0" },
      { distance: 25, path: "1" },
      { distance: 136, path: "2" },
      { distance: 99, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 46, path: "0" },
      { distance: 9, path: "1" },
      { distance: 120, path: "2" },
      { distance: 83, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 105, path: "0" },
      { distance: 68, path: "1" },
      { distance: 7, path: "2" },
      { distance: 31, path: "2" },
      { distance: 142, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 89, path: "0" },
      { distance: 52, path: "1" },
      { distance: 15, path: "2" },
      { distance: 126, path: "3" },
    ],
    "?",
    "?",
  ],
  [
    "?",
    "?",
    [
      { distance: 61, path: "0" },
      { distance: 24, path: "1" },
      { distance: 135, path: "2" },
      { distance: 98, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 47, path: "0" },
      { distance: 10, path: "1" },
      { distance: 121, path: "2" },
      { distance: 84, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 104, path: "0" },
      { distance: 67, path: "1" },
      { distance: 6, path: "2" },
      { distance: 30, path: "2" },
      { distance: 141, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 90, path: "0" },
      { distance: 53, path: "1" },
      { distance: 16, path: "2" },
      { distance: 127, path: "3" },
    ],
    "?",
    "?",
  ],
  [
    "?",
    "?",
    [
      { distance: 60, path: "0" },
      { distance: 23, path: "1" },
      { distance: 134, path: "2" },
      { distance: 97, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 48, path: "0" },
      { distance: 11, path: "1" },
      { distance: 122, path: "2" },
      { distance: 85, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 103, path: "0" },
      { distance: 66, path: "1" },
      { distance: 5, path: "2" },
      { distance: 29, path: "2" },
      { distance: 140, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 91, path: "0" },
      { distance: 54, path: "1" },
      { distance: 17, path: "2" },
      { distance: 128, path: "3" },
    ],
    "?",
    "?",
  ],
  [
    "?",
    "?",
    [
      { distance: 59, path: "0" },
      { distance: 22, path: "1" },
      { distance: 133, path: "2" },
      { distance: 96, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 49, path: "0" },
      { distance: 12, path: "1" },
      { distance: 123, path: "2" },
      { distance: 86, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 102, path: "0" },
      { distance: 65, path: "1" },
      { distance: 4, path: "2" },
      { distance: 28, path: "2" },
      { distance: 139, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 92, path: "0" },
      { distance: 55, path: "1" },
      { distance: 18, path: "2" },
      { distance: 129, path: "3" },
    ],
    "?",
    "?",
  ],
  [
    "?",
    "?",
    [
      { distance: 58, path: "0" },
      { distance: 21, path: "1" },
      { distance: 132, path: "2" },
      { distance: 95, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 50, path: "0" },
      { distance: 13, path: "1" },
      { distance: 124, path: "2" },
      { distance: 87, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 101, path: "0" },
      { distance: 64, path: "1" },
      { distance: 3, path: "2" },
      { distance: 27, path: "2" },
      { distance: 138, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 93, path: "0" },
      { distance: 56, path: "1" },
      { distance: 19, path: "2" },
      { distance: 130, path: "3" },
    ],
    "?",
    "?",
  ],
  [
    "?",
    "?",
    [
      { distance: 57, path: "0" },
      { distance: 20, path: "1" },
      { distance: 131, path: "2" },
      { distance: 94, path: "3" },
    ],
    [
      { distance: 56, path: "0" },
      { distance: 19, path: "1" },
      { distance: 130, path: "2" },
      { distance: 93, path: "3" },
    ],
    [
      { distance: 55, path: "0" },
      { distance: 18, path: "1" },
      { distance: 129, path: "2" },
      { distance: 92, path: "3" },
    ],
    [
      { distance: 54, path: "0" },
      { distance: 17, path: "1" },
      { distance: 128, path: "2" },
      { distance: 91, path: "3" },
    ],
    [
      { distance: 53, path: "0" },
      { distance: 16, path: "1" },
      { distance: 127, path: "2" },
      { distance: 90, path: "3" },
    ],
    [
      { distance: 52, path: "0" },
      { distance: 15, path: "1" },
      { distance: 126, path: "2" },
      { distance: 89, path: "3" },
    ],
    [
      { distance: 51, path: "0" },
      { distance: 14, path: "1" },
      { distance: 125, path: "2" },
      { distance: 88, path: "3" },
    ],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [
      { distance: 100, path: "0" },
      { distance: 63, path: "1" },
      { distance: 2, path: "2" },
      { distance: 26, path: "2" },
      { distance: 137, path: "3" },
    ],
    [
      { distance: 99, path: "0" },
      { distance: 62, path: "1" },
      { distance: 25, path: "2" },
      { distance: 136, path: "3" },
    ],
    [
      { distance: 98, path: "0" },
      { distance: 61, path: "1" },
      { distance: 24, path: "2" },
      { distance: 135, path: "3" },
    ],
    [
      { distance: 97, path: "0" },
      { distance: 60, path: "1" },
      { distance: 23, path: "2" },
      { distance: 134, path: "3" },
    ],
    [
      { distance: 96, path: "0" },
      { distance: 59, path: "1" },
      { distance: 22, path: "2" },
      { distance: 133, path: "3" },
    ],
    [
      { distance: 95, path: "0" },
      { distance: 58, path: "1" },
      { distance: 21, path: "2" },
      { distance: 132, path: "3" },
    ],
    [
      { distance: 94, path: "0" },
      { distance: 57, path: "1" },
      { distance: 20, path: "2" },
      { distance: 131, path: "3" },
    ],
    "?",
    "?",
  ],
  [
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [{ distance: 1, path: "2" }],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
  ],
  [
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    [{ distance: 0, path: "2" }],
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
    "?",
  ],
];
