import { Map } from "../types/types";
import {
  UNSET_CELL as U,
  START_CELL as S,
  END_CELL as E,
} from "../constants/mapMatrixConstants";

export const spiralMap: Map = [
  [U, S, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U],
  [
    U,
    [{ path: "0", distance: 1 }],
    U,
    [{ path: "0", distance: 67 }],
    [{ path: "0", distance: 66 }],
    [{ path: "0", distance: 65 }],
    [{ path: "0", distance: 64 }],
    [{ path: "0", distance: 63 }],
    [{ path: "0", distance: 62 }],
    [{ path: "0", distance: 61 }],
    [{ path: "0", distance: 60 }],
    [{ path: "0", distance: 59 }],
    [{ path: "0", distance: 58 }],
    [{ path: "0", distance: 57 }],
    [{ path: "0", distance: 56 }],
    [{ path: "0", distance: 55 }],
    [{ path: "0", distance: 54 }],
    [{ path: "0", distance: 53 }],
    [{ path: "0", distance: 52 }],
    U,
  ],
  [
    U,
    [{ path: "0", distance: 2 }],
    U,
    [{ path: "0", distance: 68 }],
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    [{ path: "0", distance: 51 }],
    U,
  ],
  [
    U,
    [{ path: "0", distance: 3 }],
    U,
    [{ path: "0", distance: 69 }],
    U,
    [{ path: "0", distance: 119 }],
    [{ path: "0", distance: 118 }],
    [{ path: "0", distance: 117 }],
    [{ path: "0", distance: 116 }],
    [{ path: "0", distance: 115 }],
    [{ path: "0", distance: 114 }],
    [{ path: "0", distance: 113 }],
    [{ path: "0", distance: 112 }],
    [{ path: "0", distance: 111 }],
    [{ path: "0", distance: 110 }],
    [{ path: "0", distance: 109 }],
    [{ path: "0", distance: 108 }],
    U,
    [{ path: "0", distance: 50 }],
    U,
  ],
  [
    U,
    [{ path: "0", distance: 4 }],
    U,
    [{ path: "0", distance: 70 }],
    U,
    [{ path: "0", distance: 120 }],
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    [{ path: "0", distance: 107 }],
    U,
    [{ path: "0", distance: 49 }],
    U,
  ],
  [
    U,
    [{ path: "0", distance: 5 }],
    U,
    [{ path: "0", distance: 71 }],
    U,
    [{ path: "0", distance: 121 }],
    U,
    [{ path: "0", distance: 155 }],
    [{ path: "0", distance: 154 }],
    [{ path: "0", distance: 153 }],
    [{ path: "0", distance: 152 }],
    [{ path: "0", distance: 151 }],
    [{ path: "0", distance: 150 }],
    [{ path: "0", distance: 149 }],
    [{ path: "0", distance: 148 }],
    U,
    [{ path: "0", distance: 106 }],
    U,
    [{ path: "0", distance: 48 }],
    U,
  ],
  [
    U,
    [{ path: "0", distance: 6 }],
    U,
    [{ path: "0", distance: 72 }],
    U,
    [{ path: "0", distance: 122 }],
    U,
    [{ path: "0", distance: 156 }],
    U,
    U,
    U,
    U,
    U,
    U,
    [{ path: "0", distance: 147 }],
    U,
    [{ path: "0", distance: 105 }],
    U,
    [{ path: "0", distance: 47 }],
    U,
  ],
  [
    U,
    [{ path: "0", distance: 7 }],
    U,
    [{ path: "0", distance: 73 }],
    U,
    [{ path: "0", distance: 123 }],
    U,
    [{ path: "0", distance: 157 }],
    U,
    [{ path: "0", distance: 175 }],
    [{ path: "0", distance: 174 }],
    [{ path: "0", distance: 173 }],
    [{ path: "0", distance: 172 }],
    U,
    [{ path: "0", distance: 146 }],
    U,
    [{ path: "0", distance: 104 }],
    U,
    [{ path: "0", distance: 46 }],
    U,
  ],
  [
    U,
    [{ path: "0", distance: 8 }],
    U,
    [{ path: "0", distance: 74 }],
    U,
    [{ path: "0", distance: 124 }],
    U,
    [{ path: "0", distance: 158 }],
    U,
    [{ path: "0", distance: 176 }],
    E,
    [{ path: "0", distance: 182 }],
    [{ path: "0", distance: 171 }],
    U,
    [{ path: "0", distance: 145 }],
    U,
    [{ path: "0", distance: 103 }],
    U,
    [{ path: "0", distance: 45 }],
    U,
  ],
  [
    U,
    [{ path: "0", distance: 9 }],
    U,
    [{ path: "0", distance: 75 }],
    U,
    [{ path: "0", distance: 125 }],
    U,
    [{ path: "0", distance: 159 }],
    U,
    [{ path: "0", distance: 177 }],
    [{ path: "0", distance: 180 }],
    [{ path: "0", distance: 181 }],
    [{ path: "0", distance: 170 }],
    U,
    [{ path: "0", distance: 144 }],
    U,
    [{ path: "0", distance: 102 }],
    U,
    [{ path: "0", distance: 44 }],
    U,
  ],
  [
    U,
    [{ path: "0", distance: 10 }],
    U,
    [{ path: "0", distance: 76 }],
    U,
    [{ path: "0", distance: 126 }],
    U,
    [{ path: "0", distance: 160 }],
    U,
    [{ path: "0", distance: 178 }],
    [{ path: "0", distance: 179 }],
    U,
    [{ path: "0", distance: 169 }],
    U,
    [{ path: "0", distance: 143 }],
    U,
    [{ path: "0", distance: 101 }],
    U,
    [{ path: "0", distance: 43 }],
    U,
  ],
  [
    U,
    [{ path: "0", distance: 11 }],
    U,
    [{ path: "0", distance: 77 }],
    U,
    [{ path: "0", distance: 127 }],
    U,
    [{ path: "0", distance: 161 }],
    U,
    U,
    U,
    U,
    [{ path: "0", distance: 168 }],
    U,
    [{ path: "0", distance: 142 }],
    U,
    [{ path: "0", distance: 100 }],
    U,
    [{ path: "0", distance: 42 }],
    U,
  ],
  [
    U,
    [{ path: "0", distance: 12 }],
    U,
    [{ path: "0", distance: 78 }],
    U,
    [{ path: "0", distance: 128 }],
    U,
    [{ path: "0", distance: 162 }],
    [{ path: "0", distance: 163 }],
    [{ path: "0", distance: 164 }],
    [{ path: "0", distance: 165 }],
    [{ path: "0", distance: 166 }],
    [{ path: "0", distance: 167 }],
    U,
    [{ path: "0", distance: 141 }],
    U,
    [{ path: "0", distance: 99 }],
    U,
    [{ path: "0", distance: 41 }],
    U,
  ],
  [
    U,
    [{ path: "0", distance: 13 }],
    U,
    [{ path: "0", distance: 79 }],
    U,
    [{ path: "0", distance: 129 }],
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    [{ path: "0", distance: 140 }],
    U,
    [{ path: "0", distance: 98 }],
    U,
    [{ path: "0", distance: 40 }],
    U,
  ],
  [
    U,
    [{ path: "0", distance: 14 }],
    U,
    [{ path: "0", distance: 80 }],
    U,
    [{ path: "0", distance: 130 }],
    [{ path: "0", distance: 131 }],
    [{ path: "0", distance: 132 }],
    [{ path: "0", distance: 133 }],
    [{ path: "0", distance: 134 }],
    [{ path: "0", distance: 135 }],
    [{ path: "0", distance: 136 }],
    [{ path: "0", distance: 137 }],
    [{ path: "0", distance: 138 }],
    [{ path: "0", distance: 139 }],
    U,
    [{ path: "0", distance: 97 }],
    U,
    [{ path: "0", distance: 39 }],
    U,
  ],
  [
    U,
    [{ path: "0", distance: 15 }],
    U,
    [{ path: "0", distance: 81 }],
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    [{ path: "0", distance: 96 }],
    U,
    [{ path: "0", distance: 38 }],
    U,
  ],
  [
    U,
    [{ path: "0", distance: 16 }],
    U,
    [{ path: "0", distance: 82 }],
    [{ path: "0", distance: 83 }],
    [{ path: "0", distance: 84 }],
    [{ path: "0", distance: 85 }],
    [{ path: "0", distance: 86 }],
    [{ path: "0", distance: 87 }],
    [{ path: "0", distance: 88 }],
    [{ path: "0", distance: 89 }],
    [{ path: "0", distance: 90 }],
    [{ path: "0", distance: 91 }],
    [{ path: "0", distance: 92 }],
    [{ path: "0", distance: 93 }],
    [{ path: "0", distance: 94 }],
    [{ path: "0", distance: 95 }],
    U,
    [{ path: "0", distance: 37 }],
    U,
  ],
  [
    U,
    [{ path: "0", distance: 17 }],
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    U,
    [{ path: "0", distance: 36 }],
    U,
  ],
  [
    U,
    [{ path: "0", distance: 18 }],
    [{ path: "0", distance: 19 }],
    [{ path: "0", distance: 20 }],
    [{ path: "0", distance: 21 }],
    [{ path: "0", distance: 22 }],
    [{ path: "0", distance: 23 }],
    [{ path: "0", distance: 24 }],
    [{ path: "0", distance: 25 }],
    [{ path: "0", distance: 26 }],
    [{ path: "0", distance: 27 }],
    [{ path: "0", distance: 28 }],
    [{ path: "0", distance: 29 }],
    [{ path: "0", distance: 30 }],
    [{ path: "0", distance: 31 }],
    [{ path: "0", distance: 32 }],
    [{ path: "0", distance: 33 }],
    [{ path: "0", distance: 34 }],
    [{ path: "0", distance: 35 }],
    U,
  ],
  [U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U],
];
